language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"
  
arch:
  - AMD64
  - ppc64le

before_install:
  - | 
   if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
     sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels
   fi

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - env CFLAGS=--coverage coverage run --source=bitstruct setup.py test
  - make test-sdist

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
  
